### ISSUE TITLE
CNFS bitmap overflows with 64-bit INN

### ISSUE THREAD

**Issue by rra** [InterNetNews/inn#25] opened 2021-07-17 18:44 UTC
**Reported by eagle on 14 Dec 2008 04:40 UTC**
inn-workers mail from Christiaan den Besten <chris@prolocation.net>:

We have recently been starting to compile INN in 64-bit on our (newer) 64-bit Linux spool servers. Since some time I have noticed we see more and more of  ..

```
Jul 28 12:26:24 spool nnrpd[CNFS-sm: fudge size overflows bitmaps @03147374313600000000082C271800000002@ st16:0x10f7ff3b000: 179120864
Jul 28 12:26:24 spool nnrpd[753](753]:): CNFS-sm: fudge size overflows bitmaps @03147374313600000000082C271800000002@ st16:0x10f7ff3b000: 179120864
```

It looks likes articles are being 'overwritten' after some period of time or something like that. From what we have noticed it looks like postings arrive 'complete', but after some weeks they get broken, which would imply something is writing to the spool file at the wrong place ... which might explain the overflows.

**Comment by Julien-Elie** [comment] 2024-02-29 20:54
This issue was only reported once, [in inn-workers in August 2007](https://lists.isc.org/mailman/htdig/inn-workers/2007-August/015037.html), against INN 2.4.4.
It does not seem to be a reproducible issue, and I've not heard of a similar problem since then.
Let's close this ticket then.

**Closed by Julien-Elie** 2024-02-29 20:54 UTC
Labels: bug, wontfix, C: storage, P: medium
